# Generated by Django 2.2.3 on 2019-07-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='问题',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('内容', models.CharField(max_length=200)),
                ('发问日期', models.DateTimeField(verbose_name='发布问题日期')),
            ],
        ),
        migrations.CreateModel(
            name='选项',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('内容', models.CharField(max_length=200)),
                ('票数', models.IntegerField(default=0)),
                ('问题', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='投票.问题')),
            ],
        ),
    ]
